language: ruby
cache: bundler
rvm:
  - 2.3.0
env:
  global:
    - DB=postgres
    - RAILS_ENV=test
bundler_args: --binstubs --without=development
before_script:
  # copy required configuration files
  - cp config/database.ci.yml config/database.yml
  # create test database
  - psql -c 'create database rubyheroes_test;' -U postgres
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
script:
  - bin/rspec . --color --profile
branches:
  only:
    - master
notifications:
  email: false
