development:
   adapter: postgresql
   encoding: unicode
   database: rubyheroes_development
   user: olivierlacan
   password:

test:
  adapter: postgresql
  database: rubyheroes_testing
  user: olivierlacan
  password: 